apiVersion: v1
kind: Service
metadata:
  name: mc-terrarium
  namespace: cloud-barista
spec:
  ports:
    - port: 8055
  selector:
    app: mc-terrarium
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-terrarium
  namespace: cloud-barista
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-terrarium
  template:
    metadata:
      labels:
        app: mc-terrarium
    spec:
      containers:
        - name: mc-terrarium
          image: cloudbaristaorg/mc-terrarium:0.1.2
          ports:
            - containerPort: 8055
          env:
            - name: TERRARIUM_API_USERNAME
              value: "default"
            - name: TERRARIUM_API_PASSWORD
              value: "default"
          volumeMounts:
            - name: terrarium-data
              mountPath: /app/.terrarium
      volumes:
        - name: terrarium-data
          persistentVolumeClaim:
            claimName: mc-terrarium-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-terrarium-data-pvc
  namespace: cloud-barista
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
