apiVersion: v1
kind: Service
metadata:
  name: cb-tumblebug-etcd
  namespace: cloud-barista
spec:
  ports:
    - port: 2379
  selector:
    app: cb-tumblebug-etcd
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cb-tumblebug-etcd
  namespace: cloud-barista
spec:
  serviceName: cb-tumblebug-etcd
  replicas: 1
  selector:
    matchLabels:
      app: cb-tumblebug-etcd
  template:
    metadata:
      labels:
        app: cb-tumblebug-etcd
    spec:
      containers:
        - name: etcd
          image: gcr.io/etcd-development/etcd:v3.5.21
          command:
            - /usr/local/bin/etcd
            - --name=node1
            - --data-dir=/etcd-data
            - --advertise-client-urls=http://0.0.0.0:2379
            - --listen-client-urls=http://0.0.0.0:2379
            - --initial-advertise-peer-urls=http://0.0.0.0:2380
            - --listen-peer-urls=http://0.0.0.0:2380
            - --initial-cluster=node1=http://0.0.0.0:2380
            - --initial-cluster-state=new
            - --initial-cluster-token=etcd-cluster-1
          ports:
            - containerPort: 2379
            - containerPort: 2380
          volumeMounts:
            - name: etcd-data
              mountPath: /etcd-data
  volumeClaimTemplates:
    - metadata:
        name: etcd-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
