apiVersion: v1
kind: Service
metadata:
  name: cb-tumblebug-postgres
  namespace: cloud-barista
spec:
  ports:
    - port: 5432
  selector:
    app: cb-tumblebug-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cb-tumblebug-postgres
  namespace: cloud-barista
spec:
  serviceName: cb-tumblebug-postgres
  replicas: 1
  selector:
    matchLabels:
      app: cb-tumblebug-postgres
  template:
    metadata:
      labels:
        app: cb-tumblebug-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_DB
              value: tumblebug
            - name: POSTGRES_USER
              value: tumblebug
            - name: POSTGRES_PASSWORD
              value: tumblebug
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
