## Set system endpoints
beetle:
  root: # To be set in runtime

  ## Set SELF_ENDPOINT, to access Swagger API dashboard outside (Ex: export SELF_ENDPOINT=x.x.x.x:8056)
  self:
    endpoint: localhost:8056

  ## Set API access config
  api:
    # Set API_ALLOW_ORIGINS (ex: https://cloud-barista.org,http://localhost:8080 or * for all)
    allow:
      origins: "*"

    # Set API_AUTH_ENABLED=true currently for basic auth for all routes (i.e., url or path)
    auth:
      enabled: true

    username: default
    password: default

  ## Set internal DB config (lkvstore: local key-value store)
  lkvstore:
    path: ./db/beetle.db

  ## Logger configuration
  logfile:
    # Set log file path (default logfile path: ./log/beetle.log)
    path: ./log/beetle.log
    maxsize: 1000
    maxbackups: 3
    maxage: 30
    compress: false

  # Set log level, such as trace, debug info, warn, error, fatal, and panic
  loglevel: debug

  # Set log writer, such as file, stdout, or both
  logwriter: both

  # Set execution environment, such as development or production
  node:
    env: development

  ## Set period for auto control goroutine invocation
  autocontrol:
    duration_ms: 10000

  ## Set Tumblebug access config
  tumblebug:
    endpoint: http://localhost:1323
    api:
      username: default
      password: default
