## Set system endpoints
cmbeetle:
  root: # To be set in runtime

cbstore:
  root: # To be set in runtime (based on cmbeetle.root)

cblog:
  root: # To be set in runtime (based on cmbeetle.root)

cbspider:
  callmethod: REST
  rest:
    url: http://localhost:1024/spider

cbtumblebug:
  callmethod: REST
  rest:
    url: http://localhost:1323/tumblebug

## Logger configuration
logfile:
  # Set log file path (default logfile path: ./cm-beetle.log) 
  path: ./cm-beetle.log
  maxsize: 10
  maxbackups: 3
  maxage: 30
  compress: false

# Set log level, such as trace, debug info, warn, error, fatal, and panic
loglevel: debug

# Set log writer, such as file, stdout, or both
logwriter: both

# Set execution environment, such as development or production
node:
  env: development

## Set internal DB config (SQLlite)
db:
  url: localhost:3306
  database: cm_beetle
  user: cm_beetle
  password: cm_beetle

## Set API access config
api:
  # Set API_ALLOW_ORIGINS (ex: https://cloud-barista.org,http://localhost:8080 or * for all)
  allow:
    origins: "*"
  
  # Set API_AUTH_ENABLED=true currently for basic auth for all routes (i.e., url or path)
  auth:
    enabled: true
  
  username: default
  password: default

## Set period for auto control goroutine invocation
autocontrol:
  duration_ms: 10000

## Set SELF_ENDPOINT, to access Swagger API dashboard outside (Ex: export SELF_ENDPOINT=x.x.x.x:8056)
self:
  endpoint: localhost:8056

## Environment variables that you don't need to touch
# Swagger UI API document file path 
apidoc:
  # export APIDOC_PATH=$CMBEETLE_ROOT/src/api/rest/docs/swagger.json
  path: # To be set in runtime (based on cmbeetle.root)
