apiVersion: v1
kind: Service
metadata:
  name: cb-mapui
  namespace: cloud-barista
spec:
  ports:
    - port: 8181
      targetPort: 8181
  selector:
    app: cb-mapui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cb-mapui
  namespace: cloud-barista
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cb-mapui
  template:
    metadata:
      labels:
        app: cb-mapui
    spec:
      containers:
        - name: cb-mapui
          image: cloudbaristaorg/cb-mapui:0.1.0
          ports:
            - containerPort: 8181
