apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cm-beetle-db-pvc
  namespace: cloud-barista
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cm-beetle-log-pvc
  namespace: cloud-barista
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
