# Deployment object for the cb-tumblebug
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-beetle-deployment
  namespace: cloud-barista  # Change this to your desired namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cm-beetle
  template:
    metadata:
      name: cm-beetle-pod
      labels:
        app: cm-beetle
    spec:
      containers:
      - name: cm-beetle
        image: ghcr.io/cloud-barista/cm-beetle:latest
        ports:
        - containerPort: 8056
        env:
          - name: API_USERNAME
            value: "default"
          - name: API_PASSWORD
            value: "default"
          - name: AUTOCONTROL_DURATION_MS
            value: "10000"
          - name: SELF_ENDPOINT
            value: "localhost:1323"
          - name: API_DOC_PATH
            value: "/app/pkg/api/rest/docs/swagger.json"
