/*
Copyright 2019 The Cloud-Barista Authors.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package report provides markdown formatting for K8s migration reports
package report

import (
	"fmt"
	"strings"

	"github.com/cloud-barista/cm-beetle/pkg/core/summary"
)

// GenerateK8sMigrationReportMarkdown produces a comprehensive markdown report for K8s migration.
func GenerateK8sMigrationReportMarkdown(report *K8sMigrationReport) string {
	var md strings.Builder

	// Header
	md.WriteString("# 🚀 Kubernetes Infrastructure Migration Report\n\n")
	md.WriteString("This report provides a comparative migration analysis from on-premise Kubernetes infrastructure to target cloud managed Kubernetes, including worker node group consolidation, sizing rationales, version differences, and cost estimations.\n\n")
	md.WriteString(fmt.Sprintf("*Report generated: %s*\n\n", report.Metadata.GeneratedAt.Format("2006-01-02 15:04:05")))
	md.WriteString("---\n\n")

	// Executive Summary
	writeK8sExecutiveSummary(&md, &report.ExecutiveSummary, &report.Metadata)

	// Version Analysis
	writeK8sVersionAnalysis(&md, &report.VersionAnalysis)

	// Resource Delta Comparison
	writeK8sResourceComparison(&md, &report.ResourceComparison)

	// Worker Node Group Consolidation Mappings
	writeWorkerNodeGroupMappings(&md, report.NodeGroupMappings)

	// Sizing Rationale
	writeSizingAnalysis(&md, report.SizingAnalysis)

	// Excluded Control-Plane Nodes
	writeExcludedWorkers(&md, report.ExcludedWorkers)

	// Target Network and Security Resources
	if report.TargetDetails != nil {
		writeTargetClusterResources(&md, report.TargetDetails)
	}

	// Cost Summary
	writeCostSummary(&md, &report.CostSummary)

	// Recommendations
	writeK8sRecommendations(&md, report.Recommendations)

	// Footer
	md.WriteString("\n---\n")
	md.WriteString("\n*Report generated by CM-Beetle*\n")

	return md.String()
}

// writeK8sExecutiveSummary writes the high-level executive summary section.
func writeK8sExecutiveSummary(md *strings.Builder, summary *K8sExecutiveSummary, metadata *ReportMetadata) {
	md.WriteString("## 📊 Migration Summary\n\n")
	md.WriteString(fmt.Sprintf("**Target Cloud:** %s | **Target Region:** %s\n\n", summary.TargetCloud, summary.TargetRegion))
	md.WriteString(fmt.Sprintf("**Namespace:** %s | **Cluster ID:** %s\n\n", metadata.Namespace, metadata.InfraID))
	md.WriteString(fmt.Sprintf("**Migration Status:** %s\n\n", summary.MigrationStatus))

	md.WriteString("| Metric | Source Infrastructure | Target Managed Kubernetes |\n")
	md.WriteString("|:---|:---|:---|\n")
	md.WriteString(fmt.Sprintf("| **Cluster Name** | %s | %s |\n", summary.SourceClusterName, summary.TargetClusterName))
	md.WriteString(fmt.Sprintf("| **Total Nodes** | %d nodes | %d nodes |\n", summary.SourceTotalNodes, summary.TargetTotalNodes))
	md.WriteString(fmt.Sprintf("| **Worker Nodes** | %d nodes | %d nodes (%d NodeGroups) |\n", summary.SourceWorkerNodes, summary.TargetTotalNodes, summary.TargetNodeGroupCount))
	md.WriteString(fmt.Sprintf("| **Estimated Monthly Cost** | N/A (On-premise) | **$%.2f USD** |\n\n", summary.MonthlyCostUSD))

	md.WriteString("---\n\n")
}

// writeK8sVersionAnalysis writes the Kubernetes version analysis section.
func writeK8sVersionAnalysis(md *strings.Builder, analysis *K8sVersionAnalysis) {
	md.WriteString("## ☸️ Kubernetes Version Analysis\n\n")
	md.WriteString("| Source Version | Target CSP Version | Upgrade Status | Notes |\n")
	md.WriteString("|:---|:---|:---|:---|\n")
	md.WriteString(fmt.Sprintf("| `%s` | `%s` | **%s** | %s |\n\n",
		analysis.SourceVersion, analysis.TargetVersion, analysis.UpgradeStatus, analysis.Notes))
	md.WriteString("---\n\n")
}

// writeK8sResourceComparison writes the resource delta comparison table.
func writeK8sResourceComparison(md *strings.Builder, comp *K8sResourceComparison) {
	md.WriteString("## 🔄 Resource Delta & Sizing Comparison\n\n")
	md.WriteString("Comparison of total compute capacity between on-premise worker nodes and target cloud worker node groups:\n\n")
	md.WriteString("| Resource | Source On-Premise | Target Cloud | Change Type | Ratio | Delta Description |\n")
	md.WriteString("|:---|:---|:---|:---|:---|:---|\n")

	writeDeltaRow(md, comp.WorkerCountDelta)
	writeDeltaRow(md, comp.VcpuDelta)
	writeDeltaRow(md, comp.MemoryGibDelta)
	writeDeltaRow(md, comp.StorageGbDelta)

	md.WriteString("\n---\n\n")
}

// writeDeltaRow formats one row of resource delta.
func writeDeltaRow(md *strings.Builder, delta ResourceChange) {
	md.WriteString(fmt.Sprintf("| **%s** | %s | %s | **%s** | %.1fx | %s |\n",
		delta.ResourceType, delta.SourceValue, delta.TargetValue, delta.ChangeType, delta.ChangeRatio, delta.Description))
}

// writeWorkerNodeGroupMappings writes the consolidation mappings table.
func writeWorkerNodeGroupMappings(md *strings.Builder, mappings []WorkerNodeGroupMapping) {
	md.WriteString("## 📦 Worker Node Group Consolidation Mappings\n\n")
	md.WriteString("On-premise worker nodes consolidated into target cloud managed node groups:\n\n")

	for _, m := range mappings {
		md.WriteString(fmt.Sprintf("### Node Group: `%s` (Spec: `%s`, Target Nodes: %d)\n\n",
			m.NodeGroupName, m.TargetSpecId, m.TargetNodeCount))

		if len(m.AssignedWorkers) == 0 {
			md.WriteString("*No on-premise workers assigned.*\n\n")
			continue
		}

		md.WriteString("| Source Hostname | Machine ID | CPU Model | CPUs / Threads | Memory | Root Disk | OS | IP |\n")
		md.WriteString("|:---|:---|:---|:---|:---|:---|:---|:---|\n")
		for _, w := range m.AssignedWorkers {
			md.WriteString(fmt.Sprintf("| `%s` | `%s` | %s | %d / %d | %d GiB | %d GB (%s) | %s | %s |\n",
				w.Hostname, w.MachineID, w.CPUModel, w.CPUs, w.CPUThreads, w.MemoryGB, w.DiskGB, w.DiskType, w.OSName, w.PrimaryIP))
		}
		md.WriteString("\n")
	}

	md.WriteString("---\n\n")
}

// writeSizingAnalysis writes the 4-category sizing rationale table.
func writeSizingAnalysis(md *strings.Builder, items []WorkerSizingItem) {
	md.WriteString("## 🎯 Worker Sizing Rationale (4-Category Analysis)\n\n")
	md.WriteString("| Worker Hostname | Source Capacity | Target Spec | Target Capacity | Sizing Rationale |\n")
	md.WriteString("|:---|:---|:---|:---|:---|\n")

	for _, item := range items {
		md.WriteString(fmt.Sprintf("| `%s` | %d vCPU / %.1f GiB | `%s` | %d vCPU / %.1f GiB | %s |\n",
			item.WorkerHostname, item.SourceVcpu, item.SourceMemoryGb, item.TargetSpecId, item.TargetVcpu, item.TargetMemoryGb, item.SizingReason))
	}

	md.WriteString("\n---\n\n")
}

// writeExcludedWorkers writes the control-plane abstraction table.
func writeExcludedWorkers(md *strings.Builder, items []ExcludedWorkerItem) {
	if len(items) == 0 {
		return
	}

	md.WriteString("## 🛡️ Abstracted / Excluded Control-Plane Nodes\n\n")
	md.WriteString("Master and control-plane nodes not provisioned as worker VMs because their duties are handled by the CSP managed control plane:\n\n")
	md.WriteString("| Hostname | Source Role | Handling Rationale |\n")
	md.WriteString("|:---|:---|:---|\n")

	for _, item := range items {
		md.WriteString(fmt.Sprintf("| `%s` | `%s` | %s |\n", item.Hostname, item.Role, item.Reason))
	}

	md.WriteString("\n---\n\n")
}

// writeTargetClusterResources writes target VNet and Security Group details.
func writeTargetClusterResources(md *strings.Builder, target *summary.TargetK8sInfraSummary) {
	md.WriteString("## 🌐 Target Cloud Supporting Resources\n\n")

	md.WriteString("### Network Resources\n\n")
	if len(target.NetworkResources.VNets) == 0 {
		md.WriteString("*No dedicated VPC/VNet listed.*\n\n")
	} else {
		for _, vnet := range target.NetworkResources.VNets {
			md.WriteString(fmt.Sprintf("- **VPC/VNet Name:** `%s` (CSP ID: `%s`)\n", vnet.Name, vnet.CspVNetId))
			md.WriteString(fmt.Sprintf("- **VNet CIDR:** `%s`\n", vnet.CidrBlock))
			if len(vnet.Subnets) > 0 {
				md.WriteString(fmt.Sprintf("- **Subnet CIDR:** `%s` (%s)\n", vnet.Subnets[0].CidrBlock, vnet.Subnets[0].Name))
			}
		}
		md.WriteString("\n")
	}

	md.WriteString("### Security Groups\n\n")
	if len(target.SecurityResources.SecurityGroups) == 0 {
		md.WriteString("*No dedicated security groups listed.*\n\n")
	} else {
		for _, sg := range target.SecurityResources.SecurityGroups {
			md.WriteString(fmt.Sprintf("- **Security Group:** `%s` (%d rules configured)\n", sg.Name, len(sg.Rules)))
		}
		md.WriteString("\n")
	}

	md.WriteString("---\n\n")
}

// writeK8sRecommendations writes architectural action items.
func writeK8sRecommendations(md *strings.Builder, recs []Recommendation) {
	md.WriteString("## 💡 Architectural Recommendations & Next Steps\n\n")

	for i, r := range recs {
		md.WriteString(fmt.Sprintf("### %d. [%s] %s (Priority: **%s**)\n\n", i+1, r.Category, r.Title, r.Priority))
		md.WriteString(fmt.Sprintf("%s\n\n", r.Description))
		if len(r.ActionItems) > 0 {
			md.WriteString("**Recommended Action Items:**\n")
			for _, item := range r.ActionItems {
				md.WriteString(fmt.Sprintf("- %s\n", item))
			}
			md.WriteString("\n")
		}
	}
}
