// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/cloud-barista/cm-beetle/issues/new/choose"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/httpVersion": {
            "get": {
                "description": "Checks and logs the HTTP version of the incoming request to the server console.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Admin] System management"
                ],
                "summary": "Check HTTP version of incoming request",
                "operationId": "CheckHTTPVersion",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Custom request ID (NOTE: It will be used as a trace ID.)",
                        "name": "X-Request-Id",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.SimpleMessage"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/common.SimpleMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.SimpleMessage"
                        }
                    }
                }
            }
        },
        "/migration/ns/{nsId}/mci": {
            "get": {
                "description": "Get the migrated multi-cloud infrastructure (MCI)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Migration] Infrastructure"
                ],
                "summary": "Get the migrated multi-cloud infrastructure (MCI)",
                "operationId": "ListInfra",
                "parameters": [
                    {
                        "type": "string",
                        "default": "mig01",
                        "description": "Namespace ID",
                        "name": "nsId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "status",
                            "id"
                        ],
                        "type": "string",
                        "default": "status",
                        "description": "Option for getting the migrated multi-cloud infrastructure",
                        "name": "option",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Custom request ID (NOTE: It will be used as a trace ID.)",
                        "name": "X-Request-Id",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The info list of the migrated multi-cloud infrastructure (MCI)",
                        "schema": {
                            "$ref": "#/definitions/migration.MciInfoList"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_cloud-barista_cm-beetle_pkg_api_rest_model_beetle.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cloud-barista_cm-beetle_pkg_api_rest_model_beetle.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Migrate an infrastructure to the multi-cloud infrastructure (MCI)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Migration] Infrastructure"
                ],
                "summary": "Migrate an infrastructure to the multi-cloud infrastructure (MCI)",
                "operationId": "MigrateInfra",
                "parameters": [
                    {
                        "type": "string",
                        "default": "mig01",
                        "description": "Namespace ID",
                        "name": "nsId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Specify the information for the targeted mulci-cloud infrastructure (MCI)",
                        "name": "mciInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.MigrateInfraRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Custom request ID (NOTE: It will be used as a trace ID.)",
                        "name": "X-Request-Id",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully migrated to the multi-cloud infrastructure",
                        "schema": {
                            "$ref": "#/definitions/controller.MigrateInfraResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_cloud-barista_cm-beetle_pkg_api_rest_model_beetle.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cloud-barista_cm-beetle_pkg_api_rest_model_beetle.Response"
                        }
                    }
                }
            }
        },
        "/migration/ns/{nsId}/mci/{mciId}": {
            "get": {
                "description": "Get the migrated multi-cloud infrastructure (MCI)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Migration] Infrastructure"
                ],
                "summary": "Get the migrated multi-cloud infrastructure (MCI)",
                "operationId": "GetInfra",
                "parameters": [
                    {
                        "type": "string",
                        "default": "mig01",
                        "description": "Namespace ID",
                        "name": "nsId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "mmci01",
                        "description": "Migrated Multi-Cloud Infrastructure (MCI) ID",
                        "name": "mciId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Custom request ID (NOTE: It will be used as a trace ID.)",
                        "name": "X-Request-Id",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The migrated multi-cloud infrastructure (MCI) information",
                        "schema": {
                            "$ref": "#/definitions/controller.MigrateInfraResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_cloud-barista_cm-beetle_pkg_api_rest_model_beetle.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cloud-barista_cm-beetle_pkg_api_rest_model_beetle.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete the migrated mult-cloud infrastructure (MCI)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Migration] Infrastructure"
                ],
                "summary": "Delete the migrated mult-cloud infrastructure (MCI)",
                "operationId": "DeleteInfra",
                "parameters": [
                    {
                        "type": "string",
                        "default": "mig01",
                        "description": "Namespace ID",
                        "name": "nsId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "mmci01",
                        "description": "Migrated Multi-Cloud Infrastructure (MCI) ID",
                        "name": "mciId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "terminate",
                            "force"
                        ],
                        "type": "string",
                        "default": "terminate",
                        "description": "Action for deletion",
                        "name": "action",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Custom request ID (NOTE: It will be used as a trace ID.)",
                        "name": "X-Request-Id",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The result of deleting the migrated multi-cloud infrastructure (MCI)",
                        "schema": {
                            "$ref": "#/definitions/github_com_cloud-barista_cm-beetle_pkg_api_rest_model_beetle.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_cloud-barista_cm-beetle_pkg_api_rest_model_beetle.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cloud-barista_cm-beetle_pkg_api_rest_model_beetle.Response"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "description": "Check Beetle is ready",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Admin] System management"
                ],
                "summary": "Check Beetle is ready",
                "operationId": "GetReadyz",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Custom request ID (NOTE: It will be used as a trace ID.)",
                        "name": "X-Request-Id",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.SimpleMessage"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/common.SimpleMessage"
                        }
                    }
                }
            }
        },
        "/recommendation/containerInfra": {
            "post": {
                "description": "Recommend an appropriate container infrastructure for container-based workloads\n\n[Note] ` + "`" + `desiredProvider` + "`" + ` and ` + "`" + `desiredRegion` + "`" + ` are required.\n- ` + "`" + `desiredProvider` + "`" + ` and ` + "`" + `desiredRegion` + "`" + ` can be set in the query parameter or the request body.\n- If both are set, the values in the request body take precedence.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Recommendation] Infrastructure"
                ],
                "summary": "Recommend an appropriate container infrastructure for cloud migration",
                "operationId": "RecommendContainerInfra",
                "parameters": [
                    {
                        "description": "Specify the source container infrastructure",
                        "name": "UserInfra",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.RecommendInfraRequest"
                        }
                    },
                    {
                        "enum": [
                            "aws",
                            "azure",
                            "gcp",
                            "ncp"
                        ],
                        "type": "string",
                        "default": "aws",
                        "description": "Provider (e.g., aws, azure, gcp)",
                        "name": "desiredProvider",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "ap-northeast-2",
                        "description": "Region (e.g., ap-northeast-2)",
                        "name": "desiredRegion",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Custom request ID (NOTE: It will be used as a trace ID.)",
                        "name": "X-Request-Id",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The result of recommended container infrastructure",
                        "schema": {
                            "$ref": "#/definitions/controller.RecommendInfraResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.SimpleMsg"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/common.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.SimpleMsg"
                        }
                    }
                }
            }
        },
        "/recommendation/mci": {
            "post": {
                "description": "Recommend an appropriate multi-cloud infrastructure (MCI) for cloud migration\n\n[Note] ` + "`" + `desiredCsp` + "`" + ` and ` + "`" + `desiredRegion` + "`" + ` are required.\n- ` + "`" + `desiredCsp` + "`" + ` and ` + "`" + `desiredRegion` + "`" + ` can set on the query parameter or the request body.\n\n- If desiredCsp and desiredRegion are set on request body, the values in the query parameter will be ignored.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Recommendation] Infrastructure"
                ],
                "summary": "Recommend an appropriate multi-cloud infrastructure (MCI) for cloud migration",
                "operationId": "RecommendVMInfra",
                "parameters": [
                    {
                        "description": "Specify the your infrastructure to be migrated",
                        "name": "UserInfra",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.RecommendVmInfraRequest"
                        }
                    },
                    {
                        "enum": [
                            "aws",
                            "azure",
                            "gcp",
                            "ncp"
                        ],
                        "type": "string",
                        "default": "aws",
                        "description": "Provider (e.g., aws, azure, gcp)",
                        "name": "desiredCsp",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "ap-northeast-2",
                        "description": "Region (e.g., ap-northeast-2)",
                        "name": "desiredRegion",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Custom request ID (NOTE: It will be used as a trace ID.)",
                        "name": "X-Request-Id",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The result of recommended infrastructure",
                        "schema": {
                            "$ref": "#/definitions/controller.RecommendVmInfraResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/common.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.SimpleMsg"
                        }
                    }
                }
            }
        },
        "/sample/users": {
            "get": {
                "description": "Get information of all users.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Sample API] Users"
                ],
                "summary": "Get a list of users",
                "operationId": "GetUsers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Custom request ID (NOTE: It will be used as a trace ID.)",
                        "name": "X-Request-Id",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "(sample) This is a sample description for success response in Swagger UI",
                        "schema": {
                            "$ref": "#/definitions/controller.GetUsersResponse"
                        }
                    },
                    "404": {
                        "description": "User Not Found",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new user with the given information.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Sample API] Users"
                ],
                "summary": "Create a new user",
                "operationId": "CreateUser",
                "parameters": [
                    {
                        "description": "User information",
                        "name": "User",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.CreateUserRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Custom request ID (NOTE: It will be used as a trace ID.)",
                        "name": "X-Request-Id",
                        "in": "header"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "(Sample) This is a sample description for success response in Swagger UI",
                        "schema": {
                            "$ref": "#/definitions/controller.GetUserResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Request",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/sample/users/{id}": {
            "get": {
                "description": "Get information of a user with a specific ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Sample API] Users"
                ],
                "summary": "Get specific user information",
                "operationId": "GetUser",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Custom request ID (NOTE: It will be used as a trace ID.)",
                        "name": "X-Request-Id",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "(Sample) This is a sample description for success response in Swagger UI",
                        "schema": {
                            "$ref": "#/definitions/controller.GetUserResponse"
                        }
                    },
                    "404": {
                        "description": "User Not Found",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a user with the given information.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Sample API] Users"
                ],
                "summary": "Update a user",
                "operationId": "UpdateUser",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User information to update",
                        "name": "User",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.UpdateUserRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Custom request ID (NOTE: It will be used as a trace ID.)",
                        "name": "X-Request-Id",
                        "in": "header"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "(Sample) This is a sample description for success response in Swagger UI",
                        "schema": {
                            "$ref": "#/definitions/controller.UpdateUserResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Request",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a user with the given information.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Sample API] Users"
                ],
                "summary": "Delete a user",
                "operationId": "DeleteUser",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Custom request ID (NOTE: It will be used as a trace ID.)",
                        "name": "X-Request-Id",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User deletion successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid Request",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "User Not Found",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "patch": {
                "description": "Patch a user with the given information.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Sample API] Users"
                ],
                "summary": "Patch a user",
                "operationId": "PatchUser",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User information to update",
                        "name": "User",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.PatchUserRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Custom request ID (NOTE: It will be used as a trace ID.)",
                        "name": "X-Request-Id",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "(Sample) This is a sample description for success response in Swagger UI",
                        "schema": {
                            "$ref": "#/definitions/controller.PatchUserResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Request",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "User Not Found",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/test/tracing": {
            "get": {
                "description": "Test tracing to Tumblebug",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Test] Utility"
                ],
                "summary": "Test tracing to Tumblebug",
                "operationId": "TestTracing",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Custom request ID (NOTE: It will be used as a trace ID.)",
                        "name": "X-Request-Id",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.SimpleMessage"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/common.SimpleMessage"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.SimpleMessage": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Any message"
                }
            }
        },
        "common.SimpleMsg": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Any message"
                }
            }
        },
        "controller.CreateUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "controller.GetUserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "controller.GetUsersResponse": {
            "type": "object",
            "properties": {
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_cloud-barista_cm-beetle_pkg_api_rest_model.MyUser"
                    }
                }
            }
        },
        "controller.MigrateInfraRequest": {
            "type": "object",
            "required": [
                "name",
                "vm"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Made in CB-TB"
                },
                "installMonAgent": {
                    "description": "InstallMonAgent Option for CB-Dragonfly agent installation ([yes/no] default:no)",
                    "type": "string",
                    "default": "no",
                    "enum": [
                        "yes",
                        "no"
                    ],
                    "example": "no"
                },
                "label": {
                    "description": "Label is for describing the object by keywords",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string",
                    "example": "mci01"
                },
                "systemLabel": {
                    "description": "SystemLabel is for describing the mci in a keyword (any string can be used) for special System purpose",
                    "type": "string",
                    "example": ""
                },
                "vm": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.TbVmDynamicReq"
                    }
                }
            }
        },
        "controller.MigrateInfraResponse": {
            "type": "object",
            "required": [
                "name",
                "vm"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Made in CB-TB"
                },
                "installMonAgent": {
                    "description": "InstallMonAgent Option for CB-Dragonfly agent installation ([yes/no] default:no)",
                    "type": "string",
                    "default": "no",
                    "enum": [
                        "yes",
                        "no"
                    ],
                    "example": "no"
                },
                "label": {
                    "description": "Label is for describing the object by keywords",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string",
                    "example": "mci01"
                },
                "systemLabel": {
                    "description": "SystemLabel is for describing the mci in a keyword (any string can be used) for special System purpose",
                    "type": "string",
                    "example": ""
                },
                "vm": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.TbVmDynamicReq"
                    }
                }
            }
        },
        "controller.PatchUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "controller.PatchUserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "controller.RecommendInfraRequest": {
            "type": "object",
            "required": [
                "onpremiseInfraModel"
            ],
            "properties": {
                "desiredProvider": {
                    "type": "string",
                    "example": "aws"
                },
                "desiredRegion": {
                    "type": "string",
                    "example": "ap-northeast-2"
                },
                "onpremiseInfraModel": {
                    "$ref": "#/definitions/inframodel.OnpremInfra"
                }
            }
        },
        "controller.RecommendInfraResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "targetInfra": {
                    "$ref": "#/definitions/model.TbMciDynamicReq"
                }
            }
        },
        "controller.RecommendVmInfraRequest": {
            "type": "object",
            "required": [
                "onpremiseInfraModel"
            ],
            "properties": {
                "desiredCspAndRegionPair": {
                    "$ref": "#/definitions/recommendation.CspRegionPair"
                },
                "onpremiseInfraModel": {
                    "$ref": "#/definitions/inframodel.OnpremInfra"
                }
            }
        },
        "controller.RecommendVmInfraResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "targetInfra": {
                    "$ref": "#/definitions/model.TbMciDynamicReq"
                }
            }
        },
        "controller.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "controller.UpdateUserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_cloud-barista_cm-beetle_pkg_api_rest_model.MyUser": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_cloud-barista_cm-beetle_pkg_api_rest_model_beetle.Response": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "string",
                    "example": "Any details"
                },
                "list": {
                    "type": "array",
                    "items": {}
                },
                "object": {
                    "type": "object",
                    "additionalProperties": true
                },
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "text": {
                    "type": "string",
                    "example": "Any text"
                }
            }
        },
        "inframodel.CpuProperty": {
            "type": "object",
            "required": [
                "cores",
                "cpus",
                "threads"
            ],
            "properties": {
                "architecture": {
                    "type": "string",
                    "example": "x86_64"
                },
                "cores": {
                    "description": "Number of physical cores per CPU",
                    "type": "integer",
                    "example": 18
                },
                "cpus": {
                    "description": "Number of physical CPUs (sockets)",
                    "type": "integer",
                    "example": 2
                },
                "maxSpeed": {
                    "description": "Maximum speed in GHz",
                    "type": "number",
                    "example": 3.6
                },
                "model": {
                    "type": "string",
                    "example": "Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz"
                },
                "threads": {
                    "description": "Number of logical CPUs (threads) per CPU with hyper-threading enabled",
                    "type": "integer",
                    "example": 36
                },
                "vendor": {
                    "type": "string",
                    "example": "GenuineIntel"
                }
            }
        },
        "inframodel.DiskProperty": {
            "type": "object",
            "required": [
                "label",
                "totalSize",
                "type"
            ],
            "properties": {
                "available": {
                    "description": "Unit GiB",
                    "type": "integer"
                },
                "label": {
                    "type": "string"
                },
                "totalSize": {
                    "description": "Unit GiB",
                    "type": "integer",
                    "example": 1024
                },
                "type": {
                    "description": "SSD, HDD",
                    "type": "string",
                    "example": "SSD"
                },
                "used": {
                    "description": "Unit GiB",
                    "type": "integer"
                }
            }
        },
        "inframodel.MemoryProperty": {
            "type": "object",
            "required": [
                "totalSize",
                "type"
            ],
            "properties": {
                "available": {
                    "description": "Unit GiB",
                    "type": "integer"
                },
                "totalSize": {
                    "description": "Unit GiB",
                    "type": "integer",
                    "example": 128
                },
                "type": {
                    "type": "string",
                    "example": "DDR4"
                },
                "used": {
                    "description": "Unit GiB",
                    "type": "integer"
                }
            }
        },
        "inframodel.NetworkInterfaceProperty": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "ipv4CidrBlocks": {
                    "description": "IPv4 address with prefix length (e.g., 192.168.0.21/24), instead of inet addr, Bcast, and Mask",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ipv6CidrBlocks": {
                    "description": "IPv6 address with prefix length (e.g., \"2001:db8::1/64\")",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "macAddress": {
                    "description": "MAC address",
                    "type": "string"
                },
                "mtu": {
                    "description": "Maximum Transmission Unit (MTU) in bytes",
                    "type": "integer"
                },
                "name": {
                    "description": "Interface name (e.g., eth0, ens01, enp0s3)",
                    "type": "string"
                },
                "state": {
                    "description": "Interface state (e.g., UP, DOWN)",
                    "type": "string"
                }
            }
        },
        "inframodel.NetworkProperty": {
            "type": "object",
            "properties": {
                "ipv4Networks": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "172.26.240.0/20"
                    ]
                },
                "ipv6Networks": {
                    "description": "TBD",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "inframodel.OnpremInfra": {
            "type": "object",
            "required": [
                "servers"
            ],
            "properties": {
                "network": {
                    "$ref": "#/definitions/inframodel.NetworkProperty"
                },
                "servers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/inframodel.ServerProperty"
                    }
                }
            }
        },
        "inframodel.OsProperty": {
            "type": "object",
            "required": [
                "prettyName"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "ubuntu"
                },
                "idLike": {
                    "type": "string",
                    "example": "debian"
                },
                "name": {
                    "type": "string",
                    "example": "Ubuntu"
                },
                "prettyName": {
                    "description": "Pretty name",
                    "type": "string",
                    "example": "Ubuntu 22.04.3 LTS"
                },
                "version": {
                    "description": "Full version string",
                    "type": "string",
                    "example": "22.04.3 LTS (Jammy Jellyfish)"
                },
                "versionCodename": {
                    "type": "string",
                    "example": "jammy"
                },
                "versionId": {
                    "type": "string",
                    "example": "22.04"
                }
            }
        },
        "inframodel.RouteProperty": {
            "type": "object",
            "properties": {
                "destination": {
                    "description": "Destination network, expressed in CIDR format",
                    "type": "string"
                },
                "gateway": {
                    "description": "Gateway address to which packets are forwarded",
                    "type": "string"
                },
                "interface": {
                    "description": "Network interface associated with the route",
                    "type": "string"
                },
                "linkState": {
                    "description": "Link state of the route (e.g., UP, DOWN)",
                    "type": "string"
                },
                "metric": {
                    "description": "Metric value indicating the priority of the route",
                    "type": "integer"
                },
                "protocol": {
                    "description": "Protocol used to set the route (e.g., kernel, static)",
                    "type": "string"
                },
                "scope": {
                    "description": "Scope of the route (e.g., global, link, host)",
                    "type": "string"
                },
                "source": {
                    "description": "Optionally stores the source address (used for policy-based routing)",
                    "type": "string"
                }
            }
        },
        "inframodel.ServerProperty": {
            "type": "object",
            "properties": {
                "cpu": {
                    "$ref": "#/definitions/inframodel.CpuProperty"
                },
                "dataDisks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/inframodel.DiskProperty"
                    }
                },
                "hostname": {
                    "type": "string"
                },
                "interfaces": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/inframodel.NetworkInterfaceProperty"
                    }
                },
                "memory": {
                    "$ref": "#/definitions/inframodel.MemoryProperty"
                },
                "os": {
                    "$ref": "#/definitions/inframodel.OsProperty"
                },
                "rootDisk": {
                    "$ref": "#/definitions/inframodel.DiskProperty"
                },
                "routingTable": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/inframodel.RouteProperty"
                    }
                }
            }
        },
        "migration.IdList": {
            "type": "object",
            "properties": {
                "idList": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "migration.MciInfoList": {
            "type": "object",
            "properties": {
                "mci": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.MciStatusInfo"
                    }
                }
            }
        },
        "model.Location": {
            "type": "object",
            "properties": {
                "display": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                }
            }
        },
        "model.MciStatusInfo": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "installMonAgent": {
                    "description": "InstallMonAgent Option for CB-Dragonfly agent installation ([yes/no] default:yes)",
                    "type": "string",
                    "example": "[yes, no]"
                },
                "label": {
                    "description": "Label is for describing the object by keywords",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "masterIp": {
                    "type": "string",
                    "example": "32.201.134.113"
                },
                "masterSSHPort": {
                    "type": "string"
                },
                "masterVmId": {
                    "type": "string",
                    "example": "vm-asiaeast1-cb-01"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "statusCount": {
                    "$ref": "#/definitions/model.StatusCountInfo"
                },
                "systemLabel": {
                    "description": "SystemLabel is for describing the mci in a keyword (any string can be used) for special System purpose",
                    "type": "string",
                    "example": "Managed by CB-Tumblebug"
                },
                "targetAction": {
                    "type": "string"
                },
                "targetStatus": {
                    "type": "string"
                },
                "vm": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.TbVmStatusInfo"
                    }
                }
            }
        },
        "model.StatusCountInfo": {
            "type": "object",
            "properties": {
                "countCreating": {
                    "description": "CountCreating is for counting Creating",
                    "type": "integer"
                },
                "countFailed": {
                    "description": "CountFailed is for counting Failed",
                    "type": "integer"
                },
                "countRebooting": {
                    "description": "CountRebooting is for counting Rebooting",
                    "type": "integer"
                },
                "countResuming": {
                    "description": "CountResuming is for counting Resuming",
                    "type": "integer"
                },
                "countRunning": {
                    "description": "CountRunning is for counting Running",
                    "type": "integer"
                },
                "countSuspended": {
                    "description": "CountSuspended is for counting Suspended",
                    "type": "integer"
                },
                "countSuspending": {
                    "description": "CountSuspending is for counting Suspending",
                    "type": "integer"
                },
                "countTerminated": {
                    "description": "CountTerminated is for counting Terminated",
                    "type": "integer"
                },
                "countTerminating": {
                    "description": "CountTerminating is for counting Terminating",
                    "type": "integer"
                },
                "countTotal": {
                    "description": "CountTotal is for Total VMs",
                    "type": "integer"
                },
                "countUndefined": {
                    "description": "CountUndefined is for counting Undefined",
                    "type": "integer"
                }
            }
        },
        "model.TbMciDynamicReq": {
            "type": "object",
            "required": [
                "name",
                "vm"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Made in CB-TB"
                },
                "installMonAgent": {
                    "description": "InstallMonAgent Option for CB-Dragonfly agent installation ([yes/no] default:no)",
                    "type": "string",
                    "default": "no",
                    "enum": [
                        "yes",
                        "no"
                    ],
                    "example": "no"
                },
                "label": {
                    "description": "Label is for describing the object by keywords",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string",
                    "example": "mci01"
                },
                "systemLabel": {
                    "description": "SystemLabel is for describing the mci in a keyword (any string can be used) for special System purpose",
                    "type": "string",
                    "example": ""
                },
                "vm": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.TbVmDynamicReq"
                    }
                }
            }
        },
        "model.TbVmDynamicReq": {
            "type": "object",
            "required": [
                "commonImage",
                "commonSpec"
            ],
            "properties": {
                "commonImage": {
                    "description": "CommonImage is field for id of a image in common namespace",
                    "type": "string",
                    "example": "ubuntu18.04"
                },
                "commonSpec": {
                    "description": "CommonSpec is field for id of a spec in common namespace",
                    "type": "string",
                    "example": "aws+ap-northeast-2+t2.small"
                },
                "connectionName": {
                    "description": "if ConnectionName is given, the VM tries to use associtated credential.\nif not, it will use predefined ConnectionName in Spec objects",
                    "type": "string"
                },
                "description": {
                    "type": "string",
                    "example": "Description"
                },
                "label": {
                    "description": "Label is for describing the object by keywords",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "description": "VM name or subGroup name if is (not empty) \u0026\u0026 (\u003e 0). If it is a group, actual VM name will be generated with -N postfix.",
                    "type": "string",
                    "example": "g1-1"
                },
                "rootDiskSize": {
                    "description": "\"default\", Integer (GB): [\"50\", ..., \"1000\"]",
                    "type": "string",
                    "default": "default",
                    "example": "default, 30, 42, ..."
                },
                "rootDiskType": {
                    "description": "\"\", \"default\", \"TYPE1\", AWS: [\"standard\", \"gp2\", \"gp3\"], Azure: [\"PremiumSSD\", \"StandardSSD\", \"StandardHDD\"], GCP: [\"pd-standard\", \"pd-balanced\", \"pd-ssd\", \"pd-extreme\"], ALIBABA: [\"cloud_efficiency\", \"cloud\", \"cloud_essd\"], TENCENT: [\"CLOUD_PREMIUM\", \"CLOUD_SSD\"]",
                    "type": "string",
                    "default": "default",
                    "example": "default, TYPE1, ..."
                },
                "subGroupSize": {
                    "description": "if subGroupSize is (not empty) \u0026\u0026 (\u003e 0), subGroup will be generated. VMs will be created accordingly.",
                    "type": "string",
                    "default": "1",
                    "example": "3"
                },
                "vmUserPassword": {
                    "type": "string"
                }
            }
        },
        "model.TbVmStatusInfo": {
            "type": "object",
            "properties": {
                "createdTime": {
                    "description": "Created time",
                    "type": "string",
                    "example": "2022-11-10 23:00:00"
                },
                "cspResourceId": {
                    "description": "CspResourceId is resource identifier managed by CSP",
                    "type": "string",
                    "example": "csp-06eb41e14121c550a"
                },
                "cspResourceName": {
                    "description": "CspResourceName is name assigned to the CSP resource. This name is internally used to handle the resource.",
                    "type": "string",
                    "example": "we12fawefadf1221edcf"
                },
                "id": {
                    "description": "Id is unique identifier for the object",
                    "type": "string",
                    "example": "aws-ap-southeast-1"
                },
                "location": {
                    "$ref": "#/definitions/model.Location"
                },
                "monAgentStatus": {
                    "description": "Montoring agent status",
                    "type": "string",
                    "example": "[installed, notInstalled, failed]"
                },
                "name": {
                    "description": "Name is human-readable string to represent the object",
                    "type": "string",
                    "example": "aws-ap-southeast-1"
                },
                "nativeStatus": {
                    "type": "string"
                },
                "privateIp": {
                    "type": "string"
                },
                "publicIp": {
                    "type": "string"
                },
                "sshPort": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "systemMessage": {
                    "description": "Latest system message such as error message",
                    "type": "string",
                    "example": "Failed because ..."
                },
                "targetAction": {
                    "type": "string"
                },
                "targetStatus": {
                    "type": "string"
                },
                "uid": {
                    "description": "Uid is universally unique identifier for the object, used for labelSelector",
                    "type": "string",
                    "example": "wef12awefadf1221edcf"
                }
            }
        },
        "recommendation.CspRegionPair": {
            "type": "object",
            "properties": {
                "csp": {
                    "type": "string",
                    "example": "aws"
                },
                "region": {
                    "type": "string",
                    "example": "ap-northeast-2"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "▶▶▶ CB-Tumblebug REST API (access via Beetle's reverse proxy)",
        "url": "http://localhost:8056/tumblebug/api/index.html"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "latest",
	Host:             "localhost:8056",
	BasePath:         "/beetle",
	Schemes:          []string{},
	Title:            "CM-Beetle REST API",
	Description:      "CM-Beetle REST API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
