# This workflow performs continuous integration (CI).
# This workflow will build the container image for amd64 arch. (as a basic build test)
name: Continuous Integration (CI)

on:
  # On pull-request event with detailed condition below.
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.all-contributorsrc'
      - '.gitignore'
      - 'LICENSE'
      - 'CODEOWNERS'
      - 'assets/**'
      - 'scripts/**'
      - 'src/testclient/scripts/**'
      - 'docs/**'

jobs:
  # The job key (i.e., ID) is "build-source-code"
  build-source-code:
    # Job name is "Building source code"
    name: Build source code
    strategy:
      matrix:        
        go-version: ["1.19", "1.20", "1.21"]
        os: [ubuntu-20.04]
        #os: [ubuntu-22.04, ubuntu-20.04, windows-2022, windows-2019]        
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{matrix.go-version}}

    - name: Build
      run: go build -v ./...

    # - name: Test
    #   run: go test -v ./...

  # The job key is "build-container-image"
  build-container-image:
    # Job name is "Build a container image"
    name: Build a container image

    # This job runs on Ubuntu-latest (Ubuntu 20.04 LTS checked on 2022-09-06)
    # See https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build 
        env:
          IMAGE_NAME: ${{ github.event.repository.name }}
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
