name: Update diagram
on:
  workflow_dispatch: {}
  # push:
  #   branches:
  #     - main

jobs:
  update_diagram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update diagram
        # id: make_diagram
        uses: githubocto/repo-visualizer@0.9.1
        with:
          output_file: "diagram.svg"
          excluded_paths: "ignore,.github"
          should_push: false          # Not to create a new commit 
          # artifact_name: "diagrams"   # Save the diagram to the artifact
          
      # - name: Get artifact
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: "diagrams"
      #     path: "downloads"

      - name: Add the updated diagram
        run: |
          # Destination directory
          DEST_DIR="./docs/diagrams"
          
          # Check if the destination directory exists, if not create it
          if [ ! -d "$DEST_DIR" ]; then
              mkdir -p "$DEST_DIR"
          fi
          
          # Copy and overwrite the file
          mv ./diagram.svg "$DEST_DIR/visualizing-the-codebase.svg"

          # Stage the diagram to commit
          git add -v ./docs/diagrams/visualizing-the-codebase.svg
          
      - name: Create Pull Request
        id: create-pull-request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.UPDATE_SWAGGER_DOC_PAT  }}
          commit-message: Update diagram to visualize the codebase
          committer: cb-bot <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update-diagram
          base: main
          delete-branch: true
          title: '[Workflow] Update diagram to visualize the codebase [skip ci]'
          body: |
            Update diagram to visualize the codebase
            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            documentation
            automated pr
          # assignees: cloud-barista/cm-beetle-maintainer
          # reviewers: cloud-barista/cm-beetle-maintainer
          team-reviewers: cloud-barista/cm-beetle-maintainer
          draft: false

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.create-pull-request.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.create-pull-request.outputs.pull-request-url }}"
